apiVersion: v1
kind: Service
metadata:
  name: pipline-demo-ingress
spec:
  selector:
    name: pipeline-demo
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
